### ISSUE TITLE
Add gitter.im chat link

### ISSUE THREAD

**Issue by djdefi** [NevadaCountyFreeCodeCamp/nevadacountyfreecodecamp.github.io#15]
Link to chat: https://gitter.im/NCFREECODECAMP/Lobby

**Comment by andreas-groos** [comment]
Added a commit with the gitter icon/link

**Comment by djdefi** [comment]
Added in #17

**Comment by andreas-groos** [comment]
I only did it in index.html, would still need to be added to future pages...
