### ISSUE TITLE
Camper profiles

### ISSUE THREAD

**Issue by djdefi** [NevadaCountyFreeCodeCamp/nevadacountyfreecodecamp.github.io#6]
Profile pages for members.

Display info such as skills, interests, mentoring availability, personal project showcase, etc.

**Comment by djdefi** [comment]
Work in progress in #9

**Comment by andreas-groos** [comment]
You're funny, closing issues just because nobody was contributing for nearly 2 years

**Comment by djdefi** [comment]
Ah this one got caught in my spring cleaning. I’ll reopen it as the idea is still valid.
